/* Automatically @generated by tree-sitter v0.25.6 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 131
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 62
#define ALIAS_COUNT 0
#define TOKEN_COUNT 36
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 21
#define MAX_ALIAS_SEQUENCE_LENGTH 10
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 30
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_Executingprevioustransactionsfromtheblock_DOT = 1,
  anon_sym_LF = 2,
  anon_sym_Traces_COLON = 3,
  anon_sym_Compiling_COLON = 4,
  anon_sym_Transactionsuccessfullyexecuted_DOT = 5,
  anon_sym_Gasused_COLON = 6,
  aux_sym_summary_token1 = 7,
  aux_sym_prefix_token1 = 8,
  anon_sym_LBRACK = 9,
  anon_sym_RBRACK = 10,
  anon_sym_COLON_COLON = 11,
  anon_sym_LPAREN = 12,
  anon_sym_RPAREN = 13,
  anon_sym_u2190 = 14,
  aux_sym_return_token1 = 15,
  anon_sym_topic = 16,
  anon_sym_COLON = 17,
  anon_sym_data = 18,
  anon_sym_emit = 19,
  sym_function_name = 20,
  anon_sym_staticcall = 21,
  anon_sym_delegatecall = 22,
  anon_sym_Return = 23,
  anon_sym_Stop = 24,
  anon_sym_COMMA = 25,
  anon_sym_LPAREN_LBRACE = 26,
  anon_sym_RBRACE_RPAREN = 27,
  anon_sym_DASH = 28,
  anon_sym_DOT = 29,
  anon_sym_e = 30,
  anon_sym_true = 31,
  anon_sym_false = 32,
  sym_hex_string = 33,
  sym_address = 34,
  sym_identifier = 35,
  sym_source_file = 36,
  sym_preamble = 37,
  sym_compiling_line = 38,
  sym_summary = 39,
  sym_trace_line = 40,
  sym_prefix = 41,
  sym_call = 42,
  sym_return = 43,
  sym__raw_event_body = 44,
  sym_event = 45,
  sym_gas = 46,
  sym_contract_path = 47,
  sym_call_type = 48,
  sym_return_type = 49,
  sym_argument_list = 50,
  sym_value_list = 51,
  sym_value = 52,
  sym_struct = 53,
  sym_key_value_pair = 54,
  sym_labeled_address = 55,
  sym_number_value = 56,
  sym_boolean = 57,
  aux_sym_source_file_repeat1 = 58,
  aux_sym_preamble_repeat1 = 59,
  aux_sym_event_repeat1 = 60,
  aux_sym_argument_list_repeat1 = 61,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_Executingprevioustransactionsfromtheblock_DOT] = "Executing previous transactions from the block.",
  [anon_sym_LF] = "\n",
  [anon_sym_Traces_COLON] = "Traces:",
  [anon_sym_Compiling_COLON] = "Compiling:",
  [anon_sym_Transactionsuccessfullyexecuted_DOT] = "Transaction successfully executed.",
  [anon_sym_Gasused_COLON] = "Gas used:",
  [aux_sym_summary_token1] = "summary_token1",
  [aux_sym_prefix_token1] = "prefix_token1",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_COLON_COLON] = "::",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_u2190] = "\u2190",
  [aux_sym_return_token1] = "return_token1",
  [anon_sym_topic] = "topic",
  [anon_sym_COLON] = ":",
  [anon_sym_data] = "data",
  [anon_sym_emit] = "emit",
  [sym_function_name] = "function_name",
  [anon_sym_staticcall] = "staticcall",
  [anon_sym_delegatecall] = "delegatecall",
  [anon_sym_Return] = "Return",
  [anon_sym_Stop] = "Stop",
  [anon_sym_COMMA] = ",",
  [anon_sym_LPAREN_LBRACE] = "({",
  [anon_sym_RBRACE_RPAREN] = "})",
  [anon_sym_DASH] = "-",
  [anon_sym_DOT] = ".",
  [anon_sym_e] = "e",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_hex_string] = "hex_string",
  [sym_address] = "address",
  [sym_identifier] = "identifier",
  [sym_source_file] = "source_file",
  [sym_preamble] = "preamble",
  [sym_compiling_line] = "compiling_line",
  [sym_summary] = "summary",
  [sym_trace_line] = "trace_line",
  [sym_prefix] = "prefix",
  [sym_call] = "call",
  [sym_return] = "return",
  [sym__raw_event_body] = "_raw_event_body",
  [sym_event] = "event",
  [sym_gas] = "gas",
  [sym_contract_path] = "contract_path",
  [sym_call_type] = "call_type",
  [sym_return_type] = "return_type",
  [sym_argument_list] = "argument_list",
  [sym_value_list] = "value_list",
  [sym_value] = "value",
  [sym_struct] = "struct",
  [sym_key_value_pair] = "key_value_pair",
  [sym_labeled_address] = "labeled_address",
  [sym_number_value] = "number_value",
  [sym_boolean] = "boolean",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_preamble_repeat1] = "preamble_repeat1",
  [aux_sym_event_repeat1] = "event_repeat1",
  [aux_sym_argument_list_repeat1] = "argument_list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_Executingprevioustransactionsfromtheblock_DOT] = anon_sym_Executingprevioustransactionsfromtheblock_DOT,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_Traces_COLON] = anon_sym_Traces_COLON,
  [anon_sym_Compiling_COLON] = anon_sym_Compiling_COLON,
  [anon_sym_Transactionsuccessfullyexecuted_DOT] = anon_sym_Transactionsuccessfullyexecuted_DOT,
  [anon_sym_Gasused_COLON] = anon_sym_Gasused_COLON,
  [aux_sym_summary_token1] = aux_sym_summary_token1,
  [aux_sym_prefix_token1] = aux_sym_prefix_token1,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_COLON_COLON] = anon_sym_COLON_COLON,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_u2190] = anon_sym_u2190,
  [aux_sym_return_token1] = aux_sym_return_token1,
  [anon_sym_topic] = anon_sym_topic,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_data] = anon_sym_data,
  [anon_sym_emit] = anon_sym_emit,
  [sym_function_name] = sym_function_name,
  [anon_sym_staticcall] = anon_sym_staticcall,
  [anon_sym_delegatecall] = anon_sym_delegatecall,
  [anon_sym_Return] = anon_sym_Return,
  [anon_sym_Stop] = anon_sym_Stop,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LPAREN_LBRACE] = anon_sym_LPAREN_LBRACE,
  [anon_sym_RBRACE_RPAREN] = anon_sym_RBRACE_RPAREN,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_e] = anon_sym_e,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_hex_string] = sym_hex_string,
  [sym_address] = sym_address,
  [sym_identifier] = sym_identifier,
  [sym_source_file] = sym_source_file,
  [sym_preamble] = sym_preamble,
  [sym_compiling_line] = sym_compiling_line,
  [sym_summary] = sym_summary,
  [sym_trace_line] = sym_trace_line,
  [sym_prefix] = sym_prefix,
  [sym_call] = sym_call,
  [sym_return] = sym_return,
  [sym__raw_event_body] = sym__raw_event_body,
  [sym_event] = sym_event,
  [sym_gas] = sym_gas,
  [sym_contract_path] = sym_contract_path,
  [sym_call_type] = sym_call_type,
  [sym_return_type] = sym_return_type,
  [sym_argument_list] = sym_argument_list,
  [sym_value_list] = sym_value_list,
  [sym_value] = sym_value,
  [sym_struct] = sym_struct,
  [sym_key_value_pair] = sym_key_value_pair,
  [sym_labeled_address] = sym_labeled_address,
  [sym_number_value] = sym_number_value,
  [sym_boolean] = sym_boolean,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_preamble_repeat1] = aux_sym_preamble_repeat1,
  [aux_sym_event_repeat1] = aux_sym_event_repeat1,
  [aux_sym_argument_list_repeat1] = aux_sym_argument_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_Executingprevioustransactionsfromtheblock_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Traces_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Compiling_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Transactionsuccessfullyexecuted_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Gasused_COLON] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_summary_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_prefix_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u2190] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_return_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_topic] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_data] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_emit] = {
    .visible = true,
    .named = false,
  },
  [sym_function_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_staticcall] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_delegatecall] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Return] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Stop] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_e] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_hex_string] = {
    .visible = true,
    .named = true,
  },
  [sym_address] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_preamble] = {
    .visible = true,
    .named = true,
  },
  [sym_compiling_line] = {
    .visible = true,
    .named = true,
  },
  [sym_summary] = {
    .visible = true,
    .named = true,
  },
  [sym_trace_line] = {
    .visible = true,
    .named = true,
  },
  [sym_prefix] = {
    .visible = true,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_return] = {
    .visible = true,
    .named = true,
  },
  [sym__raw_event_body] = {
    .visible = false,
    .named = true,
  },
  [sym_event] = {
    .visible = true,
    .named = true,
  },
  [sym_gas] = {
    .visible = true,
    .named = true,
  },
  [sym_contract_path] = {
    .visible = true,
    .named = true,
  },
  [sym_call_type] = {
    .visible = true,
    .named = true,
  },
  [sym_return_type] = {
    .visible = true,
    .named = true,
  },
  [sym_argument_list] = {
    .visible = true,
    .named = true,
  },
  [sym_value_list] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym_struct] = {
    .visible = true,
    .named = true,
  },
  [sym_key_value_pair] = {
    .visible = true,
    .named = true,
  },
  [sym_labeled_address] = {
    .visible = true,
    .named = true,
  },
  [sym_number_value] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_preamble_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_event_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_argument_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_address = 1,
  field_arguments = 2,
  field_content = 3,
  field_contract = 4,
  field_data_value = 5,
  field_fields = 6,
  field_function = 7,
  field_gas = 8,
  field_gas_used = 9,
  field_key = 10,
  field_label = 11,
  field_name = 12,
  field_preamble = 13,
  field_prefix = 14,
  field_summary = 15,
  field_topic_id = 16,
  field_topic_value = 17,
  field_type = 18,
  field_unknown = 19,
  field_val = 20,
  field_values = 21,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_address] = "address",
  [field_arguments] = "arguments",
  [field_content] = "content",
  [field_contract] = "contract",
  [field_data_value] = "data_value",
  [field_fields] = "fields",
  [field_function] = "function",
  [field_gas] = "gas",
  [field_gas_used] = "gas_used",
  [field_key] = "key",
  [field_label] = "label",
  [field_name] = "name",
  [field_preamble] = "preamble",
  [field_prefix] = "prefix",
  [field_summary] = "summary",
  [field_topic_id] = "topic_id",
  [field_topic_value] = "topic_value",
  [field_type] = "type",
  [field_unknown] = "unknown",
  [field_val] = "val",
  [field_values] = "values",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 1},
  [5] = {.index = 5, .length = 1},
  [6] = {.index = 6, .length = 1},
  [7] = {.index = 7, .length = 4},
  [8] = {.index = 11, .length = 2},
  [9] = {.index = 13, .length = 2},
  [10] = {.index = 15, .length = 1},
  [11] = {.index = 16, .length = 1},
  [12] = {.index = 17, .length = 2},
  [13] = {.index = 19, .length = 1},
  [14] = {.index = 20, .length = 1},
  [15] = {.index = 21, .length = 4},
  [16] = {.index = 25, .length = 2},
  [17] = {.index = 27, .length = 2},
  [18] = {.index = 29, .length = 2},
  [19] = {.index = 31, .length = 2},
  [20] = {.index = 33, .length = 2},
  [21] = {.index = 35, .length = 1},
  [22] = {.index = 36, .length = 2},
  [23] = {.index = 38, .length = 3},
  [24] = {.index = 41, .length = 2},
  [25] = {.index = 43, .length = 4},
  [26] = {.index = 47, .length = 2},
  [27] = {.index = 49, .length = 4},
  [28] = {.index = 53, .length = 4},
  [29] = {.index = 57, .length = 5},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_unknown, 1},
  [1] =
    {field_values, 1},
  [2] =
    {field_data_value, 1, .inherited = true},
    {field_topic_value, 1, .inherited = true},
  [4] =
    {field_preamble, 0},
  [5] =
    {field_content, 0},
  [6] =
    {field_summary, 1},
  [7] =
    {field_data_value, 1, .inherited = true},
    {field_data_value, 2, .inherited = true},
    {field_topic_value, 1, .inherited = true},
    {field_topic_value, 2, .inherited = true},
  [11] =
    {field_preamble, 0},
    {field_summary, 2},
  [13] =
    {field_content, 1},
    {field_prefix, 0},
  [15] =
    {field_name, 0},
  [16] =
    {field_type, 2},
  [17] =
    {field_key, 0},
    {field_val, 2},
  [19] =
    {field_data_value, 2},
  [20] =
    {field_name, 1},
  [21] =
    {field_data_value, 0, .inherited = true},
    {field_data_value, 1, .inherited = true},
    {field_topic_value, 0, .inherited = true},
    {field_topic_value, 1, .inherited = true},
  [25] =
    {field_type, 2},
    {field_values, 4},
  [27] =
    {field_fields, 2},
    {field_name, 0},
  [29] =
    {field_topic_id, 1},
    {field_topic_value, 3},
  [31] =
    {field_arguments, 3},
    {field_name, 1},
  [33] =
    {field_data_value, 2, .inherited = true},
    {field_topic_value, 2, .inherited = true},
  [35] =
    {field_gas_used, 3},
  [36] =
    {field_address, 2},
    {field_name, 1},
  [38] =
    {field_contract, 3},
    {field_function, 5},
    {field_gas, 1},
  [41] =
    {field_address, 3},
    {field_label, 0},
  [43] =
    {field_contract, 3},
    {field_function, 5},
    {field_gas, 1},
    {field_type, 6},
  [47] =
    {field_address, 3},
    {field_name, 0},
  [49] =
    {field_contract, 3},
    {field_function, 5},
    {field_gas, 1},
    {field_type, 8},
  [53] =
    {field_arguments, 7},
    {field_contract, 3},
    {field_function, 5},
    {field_gas, 1},
  [57] =
    {field_arguments, 7},
    {field_contract, 3},
    {field_function, 5},
    {field_gas, 1},
    {field_type, 9},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 129,
  [130] = 130,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(205);
      ADVANCE_MAP(
        '\n', 207,
        '(', 224,
        ')', 225,
        ',', 240,
        '-', 243,
        '.', 244,
        '0', 214,
        ':', 231,
        '<', 145,
        'C', 102,
        'E', 156,
        'G', 20,
        'R', 56,
        'S', 134,
        'T', 116,
        '[', 220,
        ']', 221,
        'd', 30,
        'e', 246,
        'f', 23,
        's', 136,
        't', 104,
        '}', 12,
        0x2190, 226,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(215);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '\n', 207,
        '(', 160,
        ')', 225,
        ',', 240,
        '-', 243,
        '0', 212,
        ':', 230,
        '<', 145,
        '[', 220,
        'f', 256,
        't', 266,
        '}', 12,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(1);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(213);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(271);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '\n', 207,
        '(', 223,
        '0', 157,
        '[', 220,
        'd', 29,
        'e', 90,
        't', 103,
        0x2190, 226,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(2);
      END_STATE();
    case 3:
      if (lookahead == ' ') ADVANCE(33);
      END_STATE();
    case 4:
      if (lookahead == ' ') ADVANCE(216);
      END_STATE();
    case 5:
      if (lookahead == ' ') ADVANCE(63);
      END_STATE();
    case 6:
      if (lookahead == ' ') ADVANCE(114);
      END_STATE();
    case 7:
      if (lookahead == ' ') ADVANCE(150);
      END_STATE();
    case 8:
      if (lookahead == ' ') ADVANCE(125);
      END_STATE();
    case 9:
      if (lookahead == ' ') ADVANCE(141);
      END_STATE();
    case 10:
      if (lookahead == ' ') ADVANCE(133);
      END_STATE();
    case 11:
      if (lookahead == ' ') ADVANCE(62);
      END_STATE();
    case 12:
      if (lookahead == ')') ADVANCE(242);
      END_STATE();
    case 13:
      if (lookahead == '.') ADVANCE(244);
      if (lookahead == 'e') ADVANCE(245);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(13);
      END_STATE();
    case 14:
      if (lookahead == '.') ADVANCE(210);
      END_STATE();
    case 15:
      if (lookahead == '.') ADVANCE(206);
      END_STATE();
    case 16:
      if (lookahead == ':') ADVANCE(208);
      END_STATE();
    case 17:
      if (lookahead == ':') ADVANCE(211);
      END_STATE();
    case 18:
      if (lookahead == ':') ADVANCE(209);
      END_STATE();
    case 19:
      if (lookahead == '>') ADVANCE(227);
      END_STATE();
    case 20:
      if (lookahead == 'a') ADVANCE(121);
      END_STATE();
    case 21:
      if (lookahead == 'a') ADVANCE(37);
      END_STATE();
    case 22:
      if (lookahead == 'a') ADVANCE(232);
      END_STATE();
    case 23:
      if (lookahead == 'a') ADVANCE(83);
      END_STATE();
    case 24:
      if (lookahead == 'a') ADVANCE(86);
      END_STATE();
    case 25:
      if (lookahead == 'a') ADVANCE(40);
      END_STATE();
    case 26:
      if (lookahead == 'a') ADVANCE(142);
      END_STATE();
    case 27:
      if (lookahead == 'a') ADVANCE(139);
      END_STATE();
    case 28:
      if (lookahead == 'a') ADVANCE(101);
      END_STATE();
    case 29:
      if (lookahead == 'a') ADVANCE(137);
      END_STATE();
    case 30:
      if (lookahead == 'a') ADVANCE(137);
      if (lookahead == 'e') ADVANCE(84);
      END_STATE();
    case 31:
      if (lookahead == 'a') ADVANCE(88);
      END_STATE();
    case 32:
      if (lookahead == 'a') ADVANCE(44);
      END_STATE();
    case 33:
      if (lookahead == 'b') ADVANCE(87);
      END_STATE();
    case 34:
      if (lookahead == 'c') ADVANCE(228);
      END_STATE();
    case 35:
      if (lookahead == 'c') ADVANCE(79);
      END_STATE();
    case 36:
      if (lookahead == 'c') ADVANCE(148);
      END_STATE();
    case 37:
      if (lookahead == 'c') ADVANCE(57);
      if (lookahead == 'n') ADVANCE(126);
      END_STATE();
    case 38:
      if (lookahead == 'c') ADVANCE(42);
      END_STATE();
    case 39:
      if (lookahead == 'c') ADVANCE(41);
      END_STATE();
    case 40:
      if (lookahead == 'c') ADVANCE(138);
      END_STATE();
    case 41:
      if (lookahead == 'c') ADVANCE(58);
      END_STATE();
    case 42:
      if (lookahead == 'c') ADVANCE(24);
      END_STATE();
    case 43:
      if (lookahead == 'c') ADVANCE(152);
      END_STATE();
    case 44:
      if (lookahead == 'c') ADVANCE(144);
      END_STATE();
    case 45:
      if (lookahead == 'c') ADVANCE(31);
      END_STATE();
    case 46:
      if (lookahead == 'd') ADVANCE(14);
      END_STATE();
    case 47:
      if (lookahead == 'd') ADVANCE(17);
      END_STATE();
    case 48:
      if (lookahead == 'd') ADVANCE(257);
      if (lookahead == 't') ADVANCE(264);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(48);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(271);
      END_STATE();
    case 49:
      if (lookahead == 'e') ADVANCE(36);
      END_STATE();
    case 50:
      if (lookahead == 'e') ADVANCE(67);
      END_STATE();
    case 51:
      if (lookahead == 'e') ADVANCE(247);
      END_STATE();
    case 52:
      if (lookahead == 'e') ADVANCE(249);
      END_STATE();
    case 53:
      if (lookahead == 'e') ADVANCE(47);
      END_STATE();
    case 54:
      if (lookahead == 'e') ADVANCE(154);
      END_STATE();
    case 55:
      if (lookahead == 'e') ADVANCE(46);
      END_STATE();
    case 56:
      if (lookahead == 'e') ADVANCE(135);
      END_STATE();
    case 57:
      if (lookahead == 'e') ADVANCE(122);
      END_STATE();
    case 58:
      if (lookahead == 'e') ADVANCE(130);
      END_STATE();
    case 59:
      if (lookahead == 'e') ADVANCE(3);
      END_STATE();
    case 60:
      if (lookahead == 'e') ADVANCE(43);
      END_STATE();
    case 61:
      if (lookahead == 'e') ADVANCE(45);
      END_STATE();
    case 62:
      if (lookahead == 'e') ADVANCE(158);
      END_STATE();
    case 63:
      if (lookahead == 'f') ADVANCE(120);
      END_STATE();
    case 64:
      if (lookahead == 'f') ADVANCE(153);
      END_STATE();
    case 65:
      if (lookahead == 'g') ADVANCE(6);
      END_STATE();
    case 66:
      if (lookahead == 'g') ADVANCE(18);
      END_STATE();
    case 67:
      if (lookahead == 'g') ADVANCE(27);
      END_STATE();
    case 68:
      if (lookahead == 'h') ADVANCE(59);
      END_STATE();
    case 69:
      if (lookahead == 'i') ADVANCE(34);
      END_STATE();
    case 70:
      if (lookahead == 'i') ADVANCE(85);
      END_STATE();
    case 71:
      if (lookahead == 'i') ADVANCE(38);
      END_STATE();
    case 72:
      if (lookahead == 'i') ADVANCE(109);
      END_STATE();
    case 73:
      if (lookahead == 'i') ADVANCE(132);
      END_STATE();
    case 74:
      if (lookahead == 'i') ADVANCE(108);
      END_STATE();
    case 75:
      if (lookahead == 'i') ADVANCE(96);
      END_STATE();
    case 76:
      if (lookahead == 'i') ADVANCE(99);
      END_STATE();
    case 77:
      if (lookahead == 'i') ADVANCE(111);
      END_STATE();
    case 78:
      if (lookahead == 'k') ADVANCE(97);
      END_STATE();
    case 79:
      if (lookahead == 'k') ADVANCE(15);
      END_STATE();
    case 80:
      if (lookahead == 'l') ADVANCE(236);
      END_STATE();
    case 81:
      if (lookahead == 'l') ADVANCE(237);
      END_STATE();
    case 82:
      if (lookahead == 'l') ADVANCE(159);
      END_STATE();
    case 83:
      if (lookahead == 'l') ADVANCE(127);
      END_STATE();
    case 84:
      if (lookahead == 'l') ADVANCE(50);
      END_STATE();
    case 85:
      if (lookahead == 'l') ADVANCE(75);
      END_STATE();
    case 86:
      if (lookahead == 'l') ADVANCE(80);
      END_STATE();
    case 87:
      if (lookahead == 'l') ADVANCE(110);
      END_STATE();
    case 88:
      if (lookahead == 'l') ADVANCE(81);
      END_STATE();
    case 89:
      if (lookahead == 'l') ADVANCE(82);
      END_STATE();
    case 90:
      if (lookahead == 'm') ADVANCE(73);
      END_STATE();
    case 91:
      if (lookahead == 'm') ADVANCE(115);
      END_STATE();
    case 92:
      if (lookahead == 'm') ADVANCE(10);
      END_STATE();
    case 93:
      if (lookahead == 'n') ADVANCE(78);
      END_STATE();
    case 94:
      if (lookahead == 'n') ADVANCE(238);
      END_STATE();
    case 95:
      if (lookahead == 'n') ADVANCE(19);
      END_STATE();
    case 96:
      if (lookahead == 'n') ADVANCE(66);
      END_STATE();
    case 97:
      if (lookahead == 'n') ADVANCE(105);
      END_STATE();
    case 98:
      if (lookahead == 'n') ADVANCE(8);
      END_STATE();
    case 99:
      if (lookahead == 'n') ADVANCE(65);
      END_STATE();
    case 100:
      if (lookahead == 'n') ADVANCE(128);
      END_STATE();
    case 101:
      if (lookahead == 'n') ADVANCE(131);
      END_STATE();
    case 102:
      if (lookahead == 'o') ADVANCE(91);
      END_STATE();
    case 103:
      if (lookahead == 'o') ADVANCE(113);
      END_STATE();
    case 104:
      if (lookahead == 'o') ADVANCE(113);
      if (lookahead == 'r') ADVANCE(147);
      END_STATE();
    case 105:
      if (lookahead == 'o') ADVANCE(155);
      END_STATE();
    case 106:
      if (lookahead == 'o') ADVANCE(92);
      END_STATE();
    case 107:
      if (lookahead == 'o') ADVANCE(112);
      END_STATE();
    case 108:
      if (lookahead == 'o') ADVANCE(149);
      END_STATE();
    case 109:
      if (lookahead == 'o') ADVANCE(98);
      END_STATE();
    case 110:
      if (lookahead == 'o') ADVANCE(35);
      END_STATE();
    case 111:
      if (lookahead == 'o') ADVANCE(100);
      END_STATE();
    case 112:
      if (lookahead == 'p') ADVANCE(239);
      END_STATE();
    case 113:
      if (lookahead == 'p') ADVANCE(69);
      END_STATE();
    case 114:
      if (lookahead == 'p') ADVANCE(119);
      END_STATE();
    case 115:
      if (lookahead == 'p') ADVANCE(70);
      END_STATE();
    case 116:
      if (lookahead == 'r') ADVANCE(21);
      END_STATE();
    case 117:
      if (lookahead == 'r') ADVANCE(94);
      END_STATE();
    case 118:
      if (lookahead == 'r') ADVANCE(28);
      END_STATE();
    case 119:
      if (lookahead == 'r') ADVANCE(54);
      END_STATE();
    case 120:
      if (lookahead == 'r') ADVANCE(106);
      END_STATE();
    case 121:
      if (lookahead == 's') ADVANCE(7);
      END_STATE();
    case 122:
      if (lookahead == 's') ADVANCE(16);
      END_STATE();
    case 123:
      if (lookahead == 's') ADVANCE(64);
      END_STATE();
    case 124:
      if (lookahead == 's') ADVANCE(9);
      END_STATE();
    case 125:
      if (lookahead == 's') ADVANCE(151);
      END_STATE();
    case 126:
      if (lookahead == 's') ADVANCE(25);
      END_STATE();
    case 127:
      if (lookahead == 's') ADVANCE(52);
      END_STATE();
    case 128:
      if (lookahead == 's') ADVANCE(5);
      END_STATE();
    case 129:
      if (lookahead == 's') ADVANCE(53);
      END_STATE();
    case 130:
      if (lookahead == 's') ADVANCE(123);
      END_STATE();
    case 131:
      if (lookahead == 's') ADVANCE(32);
      END_STATE();
    case 132:
      if (lookahead == 't') ADVANCE(234);
      END_STATE();
    case 133:
      if (lookahead == 't') ADVANCE(68);
      END_STATE();
    case 134:
      if (lookahead == 't') ADVANCE(107);
      END_STATE();
    case 135:
      if (lookahead == 't') ADVANCE(146);
      END_STATE();
    case 136:
      if (lookahead == 't') ADVANCE(26);
      END_STATE();
    case 137:
      if (lookahead == 't') ADVANCE(22);
      END_STATE();
    case 138:
      if (lookahead == 't') ADVANCE(72);
      END_STATE();
    case 139:
      if (lookahead == 't') ADVANCE(61);
      END_STATE();
    case 140:
      if (lookahead == 't') ADVANCE(55);
      END_STATE();
    case 141:
      if (lookahead == 't') ADVANCE(118);
      END_STATE();
    case 142:
      if (lookahead == 't') ADVANCE(71);
      END_STATE();
    case 143:
      if (lookahead == 't') ADVANCE(76);
      END_STATE();
    case 144:
      if (lookahead == 't') ADVANCE(77);
      END_STATE();
    case 145:
      if (lookahead == 'u') ADVANCE(93);
      END_STATE();
    case 146:
      if (lookahead == 'u') ADVANCE(117);
      END_STATE();
    case 147:
      if (lookahead == 'u') ADVANCE(51);
      END_STATE();
    case 148:
      if (lookahead == 'u') ADVANCE(143);
      END_STATE();
    case 149:
      if (lookahead == 'u') ADVANCE(124);
      END_STATE();
    case 150:
      if (lookahead == 'u') ADVANCE(129);
      END_STATE();
    case 151:
      if (lookahead == 'u') ADVANCE(39);
      END_STATE();
    case 152:
      if (lookahead == 'u') ADVANCE(140);
      END_STATE();
    case 153:
      if (lookahead == 'u') ADVANCE(89);
      END_STATE();
    case 154:
      if (lookahead == 'v') ADVANCE(74);
      END_STATE();
    case 155:
      if (lookahead == 'w') ADVANCE(95);
      END_STATE();
    case 156:
      if (lookahead == 'x') ADVANCE(49);
      END_STATE();
    case 157:
      if (lookahead == 'x') ADVANCE(204);
      END_STATE();
    case 158:
      if (lookahead == 'x') ADVANCE(60);
      END_STATE();
    case 159:
      if (lookahead == 'y') ADVANCE(11);
      END_STATE();
    case 160:
      if (lookahead == '{') ADVANCE(241);
      END_STATE();
    case 161:
      if (lookahead == 0x2500) ADVANCE(4);
      END_STATE();
    case 162:
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(162);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(271);
      END_STATE();
    case 163:
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(163);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(235);
      END_STATE();
    case 164:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(252);
      END_STATE();
    case 165:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(253);
      END_STATE();
    case 166:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(165);
      END_STATE();
    case 167:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(166);
      END_STATE();
    case 168:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(167);
      END_STATE();
    case 169:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(168);
      END_STATE();
    case 170:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(169);
      END_STATE();
    case 171:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(170);
      END_STATE();
    case 172:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(171);
      END_STATE();
    case 173:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(172);
      END_STATE();
    case 174:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(173);
      END_STATE();
    case 175:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(174);
      END_STATE();
    case 176:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(175);
      END_STATE();
    case 177:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(176);
      END_STATE();
    case 178:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(177);
      END_STATE();
    case 179:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(178);
      END_STATE();
    case 180:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(179);
      END_STATE();
    case 181:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(180);
      END_STATE();
    case 182:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(181);
      END_STATE();
    case 183:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(182);
      END_STATE();
    case 184:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(183);
      END_STATE();
    case 185:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(184);
      END_STATE();
    case 186:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(185);
      END_STATE();
    case 187:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(186);
      END_STATE();
    case 188:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(187);
      END_STATE();
    case 189:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(188);
      END_STATE();
    case 190:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(189);
      END_STATE();
    case 191:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(190);
      END_STATE();
    case 192:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(191);
      END_STATE();
    case 193:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(192);
      END_STATE();
    case 194:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(193);
      END_STATE();
    case 195:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(194);
      END_STATE();
    case 196:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(195);
      END_STATE();
    case 197:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(196);
      END_STATE();
    case 198:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(197);
      END_STATE();
    case 199:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(198);
      END_STATE();
    case 200:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(199);
      END_STATE();
    case 201:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(200);
      END_STATE();
    case 202:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(201);
      END_STATE();
    case 203:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(202);
      END_STATE();
    case 204:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(203);
      END_STATE();
    case 205:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 206:
      ACCEPT_TOKEN(anon_sym_Executingprevioustransactionsfromtheblock_DOT);
      END_STATE();
    case 207:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 208:
      ACCEPT_TOKEN(anon_sym_Traces_COLON);
      END_STATE();
    case 209:
      ACCEPT_TOKEN(anon_sym_Compiling_COLON);
      END_STATE();
    case 210:
      ACCEPT_TOKEN(anon_sym_Transactionsuccessfullyexecuted_DOT);
      END_STATE();
    case 211:
      ACCEPT_TOKEN(anon_sym_Gasused_COLON);
      END_STATE();
    case 212:
      ACCEPT_TOKEN(aux_sym_summary_token1);
      if (lookahead == '_') ADVANCE(255);
      if (lookahead == 'x') ADVANCE(270);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(213);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(271);
      END_STATE();
    case 213:
      ACCEPT_TOKEN(aux_sym_summary_token1);
      if (lookahead == '_') ADVANCE(255);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(213);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(271);
      END_STATE();
    case 214:
      ACCEPT_TOKEN(aux_sym_summary_token1);
      if (lookahead == 'x') ADVANCE(164);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(215);
      END_STATE();
    case 215:
      ACCEPT_TOKEN(aux_sym_summary_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(215);
      END_STATE();
    case 216:
      ACCEPT_TOKEN(aux_sym_prefix_token1);
      END_STATE();
    case 217:
      ACCEPT_TOKEN(aux_sym_prefix_token1);
      if (lookahead == ' ') ADVANCE(217);
      if (lookahead == 0x2502) ADVANCE(218);
      if (lookahead == 0x2514 ||
          lookahead == 0x251c) ADVANCE(161);
      END_STATE();
    case 218:
      ACCEPT_TOKEN(aux_sym_prefix_token1);
      if (lookahead == ' ' ||
          lookahead == 0x2502) ADVANCE(218);
      if (lookahead == 0x2514 ||
          lookahead == 0x251c) ADVANCE(161);
      END_STATE();
    case 219:
      ACCEPT_TOKEN(aux_sym_prefix_token1);
      if (eof) ADVANCE(205);
      if (lookahead == ' ') ADVANCE(217);
      if (lookahead == 0x2502) ADVANCE(218);
      if (lookahead == 0x2514 ||
          lookahead == 0x251c) ADVANCE(161);
      END_STATE();
    case 220:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 221:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 222:
      ACCEPT_TOKEN(anon_sym_COLON_COLON);
      END_STATE();
    case 223:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 224:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      if (lookahead == '{') ADVANCE(241);
      END_STATE();
    case 225:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 226:
      ACCEPT_TOKEN(anon_sym_u2190);
      END_STATE();
    case 227:
      ACCEPT_TOKEN(aux_sym_return_token1);
      END_STATE();
    case 228:
      ACCEPT_TOKEN(anon_sym_topic);
      END_STATE();
    case 229:
      ACCEPT_TOKEN(anon_sym_topic);
      if (lookahead == '_') ADVANCE(255);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(271);
      END_STATE();
    case 230:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 231:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == ':') ADVANCE(222);
      END_STATE();
    case 232:
      ACCEPT_TOKEN(anon_sym_data);
      END_STATE();
    case 233:
      ACCEPT_TOKEN(anon_sym_data);
      if (lookahead == '_') ADVANCE(255);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(271);
      END_STATE();
    case 234:
      ACCEPT_TOKEN(anon_sym_emit);
      END_STATE();
    case 235:
      ACCEPT_TOKEN(sym_function_name);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(235);
      END_STATE();
    case 236:
      ACCEPT_TOKEN(anon_sym_staticcall);
      END_STATE();
    case 237:
      ACCEPT_TOKEN(anon_sym_delegatecall);
      END_STATE();
    case 238:
      ACCEPT_TOKEN(anon_sym_Return);
      END_STATE();
    case 239:
      ACCEPT_TOKEN(anon_sym_Stop);
      END_STATE();
    case 240:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 241:
      ACCEPT_TOKEN(anon_sym_LPAREN_LBRACE);
      END_STATE();
    case 242:
      ACCEPT_TOKEN(anon_sym_RBRACE_RPAREN);
      END_STATE();
    case 243:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 244:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 245:
      ACCEPT_TOKEN(anon_sym_e);
      END_STATE();
    case 246:
      ACCEPT_TOKEN(anon_sym_e);
      if (lookahead == 'm') ADVANCE(73);
      END_STATE();
    case 247:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 248:
      ACCEPT_TOKEN(anon_sym_true);
      if (lookahead == '_') ADVANCE(255);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(271);
      END_STATE();
    case 249:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 250:
      ACCEPT_TOKEN(anon_sym_false);
      if (lookahead == '_') ADVANCE(255);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(271);
      END_STATE();
    case 251:
      ACCEPT_TOKEN(sym_hex_string);
      if (lookahead == '_') ADVANCE(255);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(251);
      if (('G' <= lookahead && lookahead <= 'Z') ||
          ('g' <= lookahead && lookahead <= 'z')) ADVANCE(271);
      END_STATE();
    case 252:
      ACCEPT_TOKEN(sym_hex_string);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(252);
      END_STATE();
    case 253:
      ACCEPT_TOKEN(sym_address);
      END_STATE();
    case 254:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '_') ADVANCE(254);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(254);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(271);
      END_STATE();
    case 255:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '_') ADVANCE(254);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(271);
      END_STATE();
    case 256:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '_') ADVANCE(255);
      if (lookahead == 'a') ADVANCE(263);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(271);
      END_STATE();
    case 257:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '_') ADVANCE(255);
      if (lookahead == 'a') ADVANCE(268);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(271);
      END_STATE();
    case 258:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '_') ADVANCE(255);
      if (lookahead == 'a') ADVANCE(233);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(271);
      END_STATE();
    case 259:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '_') ADVANCE(255);
      if (lookahead == 'c') ADVANCE(229);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(271);
      END_STATE();
    case 260:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '_') ADVANCE(255);
      if (lookahead == 'e') ADVANCE(248);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(271);
      END_STATE();
    case 261:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '_') ADVANCE(255);
      if (lookahead == 'e') ADVANCE(250);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(271);
      END_STATE();
    case 262:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '_') ADVANCE(255);
      if (lookahead == 'i') ADVANCE(259);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(271);
      END_STATE();
    case 263:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '_') ADVANCE(255);
      if (lookahead == 'l') ADVANCE(267);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(271);
      END_STATE();
    case 264:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '_') ADVANCE(255);
      if (lookahead == 'o') ADVANCE(265);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(271);
      END_STATE();
    case 265:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '_') ADVANCE(255);
      if (lookahead == 'p') ADVANCE(262);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(271);
      END_STATE();
    case 266:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '_') ADVANCE(255);
      if (lookahead == 'r') ADVANCE(269);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(271);
      END_STATE();
    case 267:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '_') ADVANCE(255);
      if (lookahead == 's') ADVANCE(261);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(271);
      END_STATE();
    case 268:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '_') ADVANCE(255);
      if (lookahead == 't') ADVANCE(258);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(271);
      END_STATE();
    case 269:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '_') ADVANCE(255);
      if (lookahead == 'u') ADVANCE(260);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(271);
      END_STATE();
    case 270:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '_') ADVANCE(255);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(251);
      if (('G' <= lookahead && lookahead <= 'Z') ||
          ('g' <= lookahead && lookahead <= 'z')) ADVANCE(271);
      END_STATE();
    case 271:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '_') ADVANCE(255);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(271);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 219},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 219},
  [9] = {.lex_state = 219},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 219},
  [12] = {.lex_state = 219},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 219},
  [16] = {.lex_state = 219},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 219},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 219},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 48},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 219},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 13},
  [52] = {.lex_state = 162},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 13},
  [59] = {.lex_state = 13},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 13},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 2},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 163},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 2},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 13},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 2},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 2},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 13},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 162},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_Executingprevioustransactionsfromtheblock_DOT] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [anon_sym_Traces_COLON] = ACTIONS(1),
    [anon_sym_Compiling_COLON] = ACTIONS(1),
    [anon_sym_Transactionsuccessfullyexecuted_DOT] = ACTIONS(1),
    [anon_sym_Gasused_COLON] = ACTIONS(1),
    [aux_sym_summary_token1] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_COLON_COLON] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_u2190] = ACTIONS(1),
    [aux_sym_return_token1] = ACTIONS(1),
    [anon_sym_topic] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_data] = ACTIONS(1),
    [anon_sym_emit] = ACTIONS(1),
    [anon_sym_staticcall] = ACTIONS(1),
    [anon_sym_delegatecall] = ACTIONS(1),
    [anon_sym_Return] = ACTIONS(1),
    [anon_sym_Stop] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LPAREN_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE_RPAREN] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_e] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_hex_string] = ACTIONS(1),
    [sym_address] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(114),
    [sym_preamble] = STATE(12),
    [sym_trace_line] = STATE(8),
    [sym_prefix] = STATE(13),
    [sym_call] = STATE(68),
    [sym_return] = STATE(68),
    [sym_event] = STATE(68),
    [aux_sym_source_file_repeat1] = STATE(8),
    [anon_sym_Executingprevioustransactionsfromtheblock_DOT] = ACTIONS(3),
    [aux_sym_prefix_token1] = ACTIONS(5),
    [anon_sym_LBRACK] = ACTIONS(7),
    [anon_sym_u2190] = ACTIONS(9),
    [anon_sym_emit] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(13), 1,
      anon_sym_LF,
    ACTIONS(15), 1,
      aux_sym_summary_token1,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      aux_sym_return_token1,
    ACTIONS(21), 1,
      anon_sym_DASH,
    ACTIONS(27), 1,
      sym_identifier,
    STATE(47), 1,
      sym_value,
    STATE(64), 1,
      sym_value_list,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(25), 2,
      sym_hex_string,
      sym_address,
    STATE(31), 5,
      sym_struct,
      sym_key_value_pair,
      sym_labeled_address,
      sym_number_value,
      sym_boolean,
  [40] = 9,
    ACTIONS(15), 1,
      aux_sym_summary_token1,
    ACTIONS(21), 1,
      anon_sym_DASH,
    ACTIONS(27), 1,
      sym_identifier,
    ACTIONS(29), 1,
      anon_sym_RPAREN,
    STATE(29), 1,
      sym_value,
    STATE(73), 1,
      sym_argument_list,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(25), 2,
      sym_hex_string,
      sym_address,
    STATE(31), 5,
      sym_struct,
      sym_key_value_pair,
      sym_labeled_address,
      sym_number_value,
      sym_boolean,
  [74] = 9,
    ACTIONS(15), 1,
      aux_sym_summary_token1,
    ACTIONS(21), 1,
      anon_sym_DASH,
    ACTIONS(27), 1,
      sym_identifier,
    ACTIONS(31), 1,
      anon_sym_LF,
    STATE(47), 1,
      sym_value,
    STATE(84), 1,
      sym_value_list,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(25), 2,
      sym_hex_string,
      sym_address,
    STATE(31), 5,
      sym_struct,
      sym_key_value_pair,
      sym_labeled_address,
      sym_number_value,
      sym_boolean,
  [108] = 9,
    ACTIONS(15), 1,
      aux_sym_summary_token1,
    ACTIONS(21), 1,
      anon_sym_DASH,
    ACTIONS(27), 1,
      sym_identifier,
    ACTIONS(33), 1,
      anon_sym_RBRACE_RPAREN,
    STATE(29), 1,
      sym_value,
    STATE(66), 1,
      sym_argument_list,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(25), 2,
      sym_hex_string,
      sym_address,
    STATE(31), 5,
      sym_struct,
      sym_key_value_pair,
      sym_labeled_address,
      sym_number_value,
      sym_boolean,
  [142] = 9,
    ACTIONS(15), 1,
      aux_sym_summary_token1,
    ACTIONS(21), 1,
      anon_sym_DASH,
    ACTIONS(27), 1,
      sym_identifier,
    ACTIONS(35), 1,
      anon_sym_RPAREN,
    STATE(29), 1,
      sym_value,
    STATE(115), 1,
      sym_argument_list,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(25), 2,
      sym_hex_string,
      sym_address,
    STATE(31), 5,
      sym_struct,
      sym_key_value_pair,
      sym_labeled_address,
      sym_number_value,
      sym_boolean,
  [176] = 8,
    ACTIONS(15), 1,
      aux_sym_summary_token1,
    ACTIONS(21), 1,
      anon_sym_DASH,
    ACTIONS(27), 1,
      sym_identifier,
    ACTIONS(37), 1,
      anon_sym_LBRACK,
    STATE(27), 1,
      sym_value,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(25), 2,
      sym_hex_string,
      sym_address,
    STATE(31), 5,
      sym_struct,
      sym_key_value_pair,
      sym_labeled_address,
      sym_number_value,
      sym_boolean,
  [207] = 10,
    ACTIONS(5), 1,
      aux_sym_prefix_token1,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      anon_sym_u2190,
    ACTIONS(11), 1,
      anon_sym_emit,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
    ACTIONS(41), 1,
      anon_sym_Transactionsuccessfullyexecuted_DOT,
    STATE(13), 1,
      sym_prefix,
    STATE(104), 1,
      sym_summary,
    STATE(11), 2,
      sym_trace_line,
      aux_sym_source_file_repeat1,
    STATE(68), 3,
      sym_call,
      sym_return,
      sym_event,
  [241] = 10,
    ACTIONS(5), 1,
      aux_sym_prefix_token1,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      anon_sym_u2190,
    ACTIONS(11), 1,
      anon_sym_emit,
    ACTIONS(41), 1,
      anon_sym_Transactionsuccessfullyexecuted_DOT,
    ACTIONS(43), 1,
      ts_builtin_sym_end,
    STATE(13), 1,
      sym_prefix,
    STATE(95), 1,
      sym_summary,
    STATE(11), 2,
      sym_trace_line,
      aux_sym_source_file_repeat1,
    STATE(68), 3,
      sym_call,
      sym_return,
      sym_event,
  [275] = 7,
    ACTIONS(15), 1,
      aux_sym_summary_token1,
    ACTIONS(21), 1,
      anon_sym_DASH,
    ACTIONS(27), 1,
      sym_identifier,
    STATE(30), 1,
      sym_value,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(25), 2,
      sym_hex_string,
      sym_address,
    STATE(31), 5,
      sym_struct,
      sym_key_value_pair,
      sym_labeled_address,
      sym_number_value,
      sym_boolean,
  [303] = 9,
    ACTIONS(45), 1,
      ts_builtin_sym_end,
    ACTIONS(47), 1,
      anon_sym_Transactionsuccessfullyexecuted_DOT,
    ACTIONS(49), 1,
      aux_sym_prefix_token1,
    ACTIONS(52), 1,
      anon_sym_LBRACK,
    ACTIONS(55), 1,
      anon_sym_u2190,
    ACTIONS(58), 1,
      anon_sym_emit,
    STATE(13), 1,
      sym_prefix,
    STATE(11), 2,
      sym_trace_line,
      aux_sym_source_file_repeat1,
    STATE(68), 3,
      sym_call,
      sym_return,
      sym_event,
  [334] = 7,
    ACTIONS(5), 1,
      aux_sym_prefix_token1,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      anon_sym_u2190,
    ACTIONS(11), 1,
      anon_sym_emit,
    STATE(13), 1,
      sym_prefix,
    STATE(9), 2,
      sym_trace_line,
      aux_sym_source_file_repeat1,
    STATE(68), 3,
      sym_call,
      sym_return,
      sym_event,
  [359] = 4,
    ACTIONS(61), 1,
      anon_sym_LBRACK,
    ACTIONS(63), 1,
      anon_sym_u2190,
    ACTIONS(65), 1,
      anon_sym_emit,
    STATE(92), 3,
      sym_call,
      sym_return,
      sym_event,
  [374] = 3,
    ACTIONS(69), 1,
      anon_sym_COLON,
    ACTIONS(71), 1,
      anon_sym_LPAREN_LBRACE,
    ACTIONS(67), 4,
      anon_sym_LF,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE_RPAREN,
  [387] = 2,
    ACTIONS(73), 2,
      ts_builtin_sym_end,
      aux_sym_prefix_token1,
    ACTIONS(75), 4,
      anon_sym_Transactionsuccessfullyexecuted_DOT,
      anon_sym_LBRACK,
      anon_sym_u2190,
      anon_sym_emit,
  [398] = 2,
    ACTIONS(77), 2,
      ts_builtin_sym_end,
      aux_sym_prefix_token1,
    ACTIONS(79), 4,
      anon_sym_Transactionsuccessfullyexecuted_DOT,
      anon_sym_LBRACK,
      anon_sym_u2190,
      anon_sym_emit,
  [409] = 2,
    ACTIONS(83), 1,
      anon_sym_LBRACK,
    ACTIONS(81), 4,
      anon_sym_LF,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE_RPAREN,
  [419] = 2,
    ACTIONS(87), 1,
      anon_sym_LBRACK,
    ACTIONS(85), 4,
      anon_sym_LF,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE_RPAREN,
  [429] = 3,
    ACTIONS(91), 1,
      anon_sym_COMMA,
    STATE(19), 1,
      aux_sym_argument_list_repeat1,
    ACTIONS(89), 3,
      anon_sym_LF,
      anon_sym_RPAREN,
      anon_sym_RBRACE_RPAREN,
  [441] = 1,
    ACTIONS(94), 5,
      anon_sym_LBRACK,
      anon_sym_u2190,
      anon_sym_topic,
      anon_sym_data,
      anon_sym_emit,
  [449] = 1,
    ACTIONS(96), 4,
      anon_sym_LF,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE_RPAREN,
  [456] = 1,
    ACTIONS(98), 4,
      anon_sym_LF,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE_RPAREN,
  [463] = 1,
    ACTIONS(100), 4,
      anon_sym_LF,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE_RPAREN,
  [470] = 2,
    ACTIONS(102), 1,
      aux_sym_prefix_token1,
    ACTIONS(104), 3,
      anon_sym_LBRACK,
      anon_sym_u2190,
      anon_sym_emit,
  [479] = 3,
    ACTIONS(106), 1,
      anon_sym_Traces_COLON,
    ACTIONS(108), 1,
      anon_sym_Compiling_COLON,
    STATE(25), 2,
      sym_compiling_line,
      aux_sym_preamble_repeat1,
  [490] = 3,
    ACTIONS(111), 1,
      anon_sym_Traces_COLON,
    ACTIONS(113), 1,
      anon_sym_Compiling_COLON,
    STATE(25), 2,
      sym_compiling_line,
      aux_sym_preamble_repeat1,
  [501] = 1,
    ACTIONS(115), 4,
      anon_sym_LF,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE_RPAREN,
  [508] = 1,
    ACTIONS(117), 4,
      anon_sym_LF,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE_RPAREN,
  [515] = 3,
    ACTIONS(121), 1,
      anon_sym_COMMA,
    STATE(33), 1,
      aux_sym_argument_list_repeat1,
    ACTIONS(119), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACE_RPAREN,
  [526] = 1,
    ACTIONS(89), 4,
      anon_sym_LF,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE_RPAREN,
  [533] = 1,
    ACTIONS(67), 4,
      anon_sym_LF,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE_RPAREN,
  [540] = 2,
    ACTIONS(123), 1,
      aux_sym_prefix_token1,
    ACTIONS(125), 3,
      anon_sym_LBRACK,
      anon_sym_u2190,
      anon_sym_emit,
  [549] = 3,
    ACTIONS(121), 1,
      anon_sym_COMMA,
    STATE(19), 1,
      aux_sym_argument_list_repeat1,
    ACTIONS(127), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACE_RPAREN,
  [560] = 3,
    ACTIONS(113), 1,
      anon_sym_Compiling_COLON,
    ACTIONS(129), 1,
      anon_sym_Traces_COLON,
    STATE(26), 2,
      sym_compiling_line,
      aux_sym_preamble_repeat1,
  [571] = 4,
    ACTIONS(131), 1,
      anon_sym_LF,
    ACTIONS(133), 1,
      anon_sym_LBRACK,
    ACTIONS(135), 1,
      anon_sym_LPAREN,
    STATE(106), 1,
      sym_call_type,
  [584] = 1,
    ACTIONS(137), 4,
      anon_sym_LF,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE_RPAREN,
  [591] = 1,
    ACTIONS(139), 4,
      anon_sym_LF,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE_RPAREN,
  [598] = 1,
    ACTIONS(141), 4,
      anon_sym_LF,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE_RPAREN,
  [605] = 1,
    ACTIONS(143), 4,
      anon_sym_LF,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE_RPAREN,
  [612] = 4,
    ACTIONS(145), 1,
      anon_sym_topic,
    ACTIONS(147), 1,
      anon_sym_data,
    ACTIONS(149), 1,
      sym_identifier,
    STATE(60), 1,
      sym__raw_event_body,
  [625] = 1,
    ACTIONS(151), 4,
      anon_sym_LF,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE_RPAREN,
  [632] = 3,
    ACTIONS(153), 1,
      anon_sym_topic,
    ACTIONS(155), 1,
      anon_sym_data,
    STATE(91), 1,
      sym__raw_event_body,
  [642] = 2,
    STATE(67), 1,
      sym_return_type,
    ACTIONS(157), 2,
      anon_sym_Return,
      anon_sym_Stop,
  [650] = 3,
    ACTIONS(133), 1,
      anon_sym_LBRACK,
    ACTIONS(159), 1,
      anon_sym_LF,
    STATE(126), 1,
      sym_call_type,
  [660] = 3,
    ACTIONS(121), 1,
      anon_sym_COMMA,
    ACTIONS(161), 1,
      anon_sym_LF,
    STATE(19), 1,
      aux_sym_argument_list_repeat1,
  [670] = 3,
    ACTIONS(133), 1,
      anon_sym_LBRACK,
    ACTIONS(163), 1,
      anon_sym_LF,
    STATE(121), 1,
      sym_call_type,
  [680] = 3,
    ACTIONS(121), 1,
      anon_sym_COMMA,
    ACTIONS(165), 1,
      anon_sym_LF,
    STATE(45), 1,
      aux_sym_argument_list_repeat1,
  [690] = 1,
    ACTIONS(167), 2,
      anon_sym_Traces_COLON,
      anon_sym_Compiling_COLON,
  [695] = 2,
    ACTIONS(5), 1,
      aux_sym_prefix_token1,
    STATE(42), 1,
      sym_prefix,
  [702] = 2,
    ACTIONS(169), 1,
      anon_sym_LF,
    STATE(57), 1,
      aux_sym_event_repeat1,
  [709] = 2,
    ACTIONS(171), 1,
      anon_sym_DOT,
    ACTIONS(173), 1,
      anon_sym_e,
  [716] = 2,
    ACTIONS(175), 1,
      sym_identifier,
    STATE(119), 1,
      sym_contract_path,
  [723] = 1,
    ACTIONS(177), 2,
      anon_sym_staticcall,
      anon_sym_delegatecall,
  [728] = 2,
    ACTIONS(179), 1,
      aux_sym_summary_token1,
    ACTIONS(181), 1,
      anon_sym_DASH,
  [735] = 2,
    ACTIONS(183), 1,
      aux_sym_summary_token1,
    STATE(129), 1,
      sym_gas,
  [742] = 2,
    ACTIONS(185), 1,
      anon_sym_COLON_COLON,
    ACTIONS(187), 1,
      anon_sym_COLON,
  [749] = 2,
    ACTIONS(189), 1,
      anon_sym_LF,
    STATE(57), 1,
      aux_sym_event_repeat1,
  [756] = 2,
    ACTIONS(192), 1,
      anon_sym_DOT,
    ACTIONS(194), 1,
      anon_sym_e,
  [763] = 2,
    ACTIONS(196), 1,
      anon_sym_DOT,
    ACTIONS(198), 1,
      anon_sym_e,
  [770] = 2,
    ACTIONS(169), 1,
      anon_sym_LF,
    STATE(50), 1,
      aux_sym_event_repeat1,
  [777] = 2,
    ACTIONS(200), 1,
      aux_sym_summary_token1,
    ACTIONS(202), 1,
      anon_sym_DASH,
  [784] = 2,
    ACTIONS(204), 1,
      ts_builtin_sym_end,
    ACTIONS(206), 1,
      anon_sym_LF,
  [791] = 1,
    ACTIONS(208), 1,
      anon_sym_e,
  [795] = 1,
    ACTIONS(210), 1,
      anon_sym_LF,
  [799] = 1,
    ACTIONS(212), 1,
      anon_sym_RBRACK,
  [803] = 1,
    ACTIONS(214), 1,
      anon_sym_RBRACE_RPAREN,
  [807] = 1,
    ACTIONS(216), 1,
      anon_sym_RBRACK,
  [811] = 1,
    ACTIONS(218), 1,
      anon_sym_LF,
  [815] = 1,
    ACTIONS(220), 1,
      aux_sym_summary_token1,
  [819] = 1,
    ACTIONS(222), 1,
      sym_hex_string,
  [823] = 1,
    ACTIONS(224), 1,
      anon_sym_LF,
  [827] = 1,
    ACTIONS(226), 1,
      anon_sym_LF,
  [831] = 1,
    ACTIONS(228), 1,
      anon_sym_RPAREN,
  [835] = 1,
    ACTIONS(230), 1,
      anon_sym_COLON,
  [839] = 1,
    ACTIONS(232), 1,
      anon_sym_LPAREN,
  [843] = 1,
    ACTIONS(234), 1,
      aux_sym_summary_token1,
  [847] = 1,
    ACTIONS(236), 1,
      anon_sym_LF,
  [851] = 1,
    ACTIONS(238), 1,
      anon_sym_LF,
  [855] = 1,
    ACTIONS(240), 1,
      anon_sym_LBRACK,
  [859] = 1,
    ACTIONS(242), 1,
      sym_function_name,
  [863] = 1,
    ACTIONS(244), 1,
      aux_sym_summary_token1,
  [867] = 1,
    ACTIONS(246), 1,
      aux_sym_summary_token1,
  [871] = 1,
    ACTIONS(248), 1,
      anon_sym_COLON,
  [875] = 1,
    ACTIONS(250), 1,
      anon_sym_LF,
  [879] = 1,
    ACTIONS(252), 1,
      aux_sym_summary_token1,
  [883] = 1,
    ACTIONS(254), 1,
      anon_sym_RBRACK,
  [887] = 1,
    ACTIONS(256), 1,
      sym_hex_string,
  [891] = 1,
    ACTIONS(258), 1,
      anon_sym_LF,
  [895] = 1,
    ACTIONS(260), 1,
      anon_sym_LF,
  [899] = 1,
    ACTIONS(262), 1,
      anon_sym_LF,
  [903] = 1,
    ACTIONS(264), 1,
      anon_sym_LF,
  [907] = 1,
    ACTIONS(266), 1,
      anon_sym_LF,
  [911] = 1,
    ACTIONS(268), 1,
      aux_sym_summary_token1,
  [915] = 1,
    ACTIONS(270), 1,
      sym_address,
  [919] = 1,
    ACTIONS(272), 1,
      ts_builtin_sym_end,
  [923] = 1,
    ACTIONS(173), 1,
      anon_sym_e,
  [927] = 1,
    ACTIONS(274), 1,
      anon_sym_RBRACK,
  [931] = 1,
    ACTIONS(276), 1,
      aux_sym_summary_token1,
  [935] = 1,
    ACTIONS(278), 1,
      sym_address,
  [939] = 1,
    ACTIONS(280), 1,
      anon_sym_LF,
  [943] = 1,
    ACTIONS(282), 1,
      anon_sym_Gasused_COLON,
  [947] = 1,
    ACTIONS(284), 1,
      ts_builtin_sym_end,
  [951] = 1,
    ACTIONS(286), 1,
      anon_sym_RBRACK,
  [955] = 1,
    ACTIONS(288), 1,
      ts_builtin_sym_end,
  [959] = 1,
    ACTIONS(290), 1,
      sym_address,
  [963] = 1,
    ACTIONS(292), 1,
      anon_sym_LF,
  [967] = 1,
    ACTIONS(294), 1,
      aux_sym_summary_token1,
  [971] = 1,
    ACTIONS(296), 1,
      anon_sym_LF,
  [975] = 1,
    ACTIONS(298), 1,
      anon_sym_e,
  [979] = 1,
    ACTIONS(300), 1,
      anon_sym_RBRACK,
  [983] = 1,
    ACTIONS(302), 1,
      aux_sym_summary_token1,
  [987] = 1,
    ACTIONS(304), 1,
      anon_sym_COLON_COLON,
  [991] = 1,
    ACTIONS(306), 1,
      anon_sym_RBRACK,
  [995] = 1,
    ACTIONS(308), 1,
      ts_builtin_sym_end,
  [999] = 1,
    ACTIONS(310), 1,
      anon_sym_RPAREN,
  [1003] = 1,
    ACTIONS(312), 1,
      anon_sym_RBRACK,
  [1007] = 1,
    ACTIONS(314), 1,
      aux_sym_summary_token1,
  [1011] = 1,
    ACTIONS(316), 1,
      anon_sym_LF,
  [1015] = 1,
    ACTIONS(318), 1,
      anon_sym_COLON_COLON,
  [1019] = 1,
    ACTIONS(320), 1,
      anon_sym_LF,
  [1023] = 1,
    ACTIONS(322), 1,
      anon_sym_LF,
  [1027] = 1,
    ACTIONS(324), 1,
      sym_identifier,
  [1031] = 1,
    ACTIONS(200), 1,
      aux_sym_summary_token1,
  [1035] = 1,
    ACTIONS(326), 1,
      anon_sym_RBRACK,
  [1039] = 1,
    ACTIONS(328), 1,
      aux_sym_summary_token1,
  [1043] = 1,
    ACTIONS(330), 1,
      anon_sym_LF,
  [1047] = 1,
    ACTIONS(332), 1,
      anon_sym_RBRACK,
  [1051] = 1,
    ACTIONS(334), 1,
      anon_sym_RBRACK,
  [1055] = 1,
    ACTIONS(336), 1,
      anon_sym_RBRACK,
  [1059] = 1,
    ACTIONS(338), 1,
      aux_sym_summary_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 40,
  [SMALL_STATE(4)] = 74,
  [SMALL_STATE(5)] = 108,
  [SMALL_STATE(6)] = 142,
  [SMALL_STATE(7)] = 176,
  [SMALL_STATE(8)] = 207,
  [SMALL_STATE(9)] = 241,
  [SMALL_STATE(10)] = 275,
  [SMALL_STATE(11)] = 303,
  [SMALL_STATE(12)] = 334,
  [SMALL_STATE(13)] = 359,
  [SMALL_STATE(14)] = 374,
  [SMALL_STATE(15)] = 387,
  [SMALL_STATE(16)] = 398,
  [SMALL_STATE(17)] = 409,
  [SMALL_STATE(18)] = 419,
  [SMALL_STATE(19)] = 429,
  [SMALL_STATE(20)] = 441,
  [SMALL_STATE(21)] = 449,
  [SMALL_STATE(22)] = 456,
  [SMALL_STATE(23)] = 463,
  [SMALL_STATE(24)] = 470,
  [SMALL_STATE(25)] = 479,
  [SMALL_STATE(26)] = 490,
  [SMALL_STATE(27)] = 501,
  [SMALL_STATE(28)] = 508,
  [SMALL_STATE(29)] = 515,
  [SMALL_STATE(30)] = 526,
  [SMALL_STATE(31)] = 533,
  [SMALL_STATE(32)] = 540,
  [SMALL_STATE(33)] = 549,
  [SMALL_STATE(34)] = 560,
  [SMALL_STATE(35)] = 571,
  [SMALL_STATE(36)] = 584,
  [SMALL_STATE(37)] = 591,
  [SMALL_STATE(38)] = 598,
  [SMALL_STATE(39)] = 605,
  [SMALL_STATE(40)] = 612,
  [SMALL_STATE(41)] = 625,
  [SMALL_STATE(42)] = 632,
  [SMALL_STATE(43)] = 642,
  [SMALL_STATE(44)] = 650,
  [SMALL_STATE(45)] = 660,
  [SMALL_STATE(46)] = 670,
  [SMALL_STATE(47)] = 680,
  [SMALL_STATE(48)] = 690,
  [SMALL_STATE(49)] = 695,
  [SMALL_STATE(50)] = 702,
  [SMALL_STATE(51)] = 709,
  [SMALL_STATE(52)] = 716,
  [SMALL_STATE(53)] = 723,
  [SMALL_STATE(54)] = 728,
  [SMALL_STATE(55)] = 735,
  [SMALL_STATE(56)] = 742,
  [SMALL_STATE(57)] = 749,
  [SMALL_STATE(58)] = 756,
  [SMALL_STATE(59)] = 763,
  [SMALL_STATE(60)] = 770,
  [SMALL_STATE(61)] = 777,
  [SMALL_STATE(62)] = 784,
  [SMALL_STATE(63)] = 791,
  [SMALL_STATE(64)] = 795,
  [SMALL_STATE(65)] = 799,
  [SMALL_STATE(66)] = 803,
  [SMALL_STATE(67)] = 807,
  [SMALL_STATE(68)] = 811,
  [SMALL_STATE(69)] = 815,
  [SMALL_STATE(70)] = 819,
  [SMALL_STATE(71)] = 823,
  [SMALL_STATE(72)] = 827,
  [SMALL_STATE(73)] = 831,
  [SMALL_STATE(74)] = 835,
  [SMALL_STATE(75)] = 839,
  [SMALL_STATE(76)] = 843,
  [SMALL_STATE(77)] = 847,
  [SMALL_STATE(78)] = 851,
  [SMALL_STATE(79)] = 855,
  [SMALL_STATE(80)] = 859,
  [SMALL_STATE(81)] = 863,
  [SMALL_STATE(82)] = 867,
  [SMALL_STATE(83)] = 871,
  [SMALL_STATE(84)] = 875,
  [SMALL_STATE(85)] = 879,
  [SMALL_STATE(86)] = 883,
  [SMALL_STATE(87)] = 887,
  [SMALL_STATE(88)] = 891,
  [SMALL_STATE(89)] = 895,
  [SMALL_STATE(90)] = 899,
  [SMALL_STATE(91)] = 903,
  [SMALL_STATE(92)] = 907,
  [SMALL_STATE(93)] = 911,
  [SMALL_STATE(94)] = 915,
  [SMALL_STATE(95)] = 919,
  [SMALL_STATE(96)] = 923,
  [SMALL_STATE(97)] = 927,
  [SMALL_STATE(98)] = 931,
  [SMALL_STATE(99)] = 935,
  [SMALL_STATE(100)] = 939,
  [SMALL_STATE(101)] = 943,
  [SMALL_STATE(102)] = 947,
  [SMALL_STATE(103)] = 951,
  [SMALL_STATE(104)] = 955,
  [SMALL_STATE(105)] = 959,
  [SMALL_STATE(106)] = 963,
  [SMALL_STATE(107)] = 967,
  [SMALL_STATE(108)] = 971,
  [SMALL_STATE(109)] = 975,
  [SMALL_STATE(110)] = 979,
  [SMALL_STATE(111)] = 983,
  [SMALL_STATE(112)] = 987,
  [SMALL_STATE(113)] = 991,
  [SMALL_STATE(114)] = 995,
  [SMALL_STATE(115)] = 999,
  [SMALL_STATE(116)] = 1003,
  [SMALL_STATE(117)] = 1007,
  [SMALL_STATE(118)] = 1011,
  [SMALL_STATE(119)] = 1015,
  [SMALL_STATE(120)] = 1019,
  [SMALL_STATE(121)] = 1023,
  [SMALL_STATE(122)] = 1027,
  [SMALL_STATE(123)] = 1031,
  [SMALL_STATE(124)] = 1035,
  [SMALL_STATE(125)] = 1039,
  [SMALL_STATE(126)] = 1043,
  [SMALL_STATE(127)] = 1047,
  [SMALL_STATE(128)] = 1051,
  [SMALL_STATE(129)] = 1055,
  [SMALL_STATE(130)] = 1059,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return, 4, 0, 11),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(100),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 4),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [52] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [55] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [58] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 1, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_trace_line, 2, 0, 5),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_trace_line, 2, 0, 5),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_trace_line, 3, 0, 9),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_trace_line, 3, 0, 9),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number_value, 1, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number_value, 2, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2, 0, 0),
  [91] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prefix, 1, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number_value, 7, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 4, 0, 17),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preamble, 4, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_preamble, 4, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_preamble_repeat1, 2, 0, 0),
  [108] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_preamble_repeat1, 2, 0, 0), SHIFT_REPEAT(122),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_key_value_pair, 3, 0, 12),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 3, 0, 10),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 1, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preamble, 5, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_preamble, 5, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 2, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 6, 0, 23),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_labeled_address, 5, 0, 24),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number_value, 9, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number_value, 6, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number_value, 10, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [147] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [149] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number_value, 8, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 9, 0, 28),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value_list, 2, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 8, 0, 23),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value_list, 1, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_compiling_line, 4, 0, 22),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_contract_path, 1, 0, 10),
  [187] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [189] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_event_repeat1, 2, 0, 15), SHIFT_REPEAT(49),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_summary, 4, 0, 21),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return, 2, 0, 2),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_type, 1, 0, 0),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [224] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__raw_event_body, 3, 0, 13),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_event, 4, 0, 14),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [250] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return, 5, 0, 16),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [258] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return, 2, 0, 1),
  [260] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__raw_event_body, 4, 0, 18),
  [262] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_event, 5, 0, 19),
  [264] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_event_repeat1, 3, 0, 20),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [272] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3, 0, 8),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [284] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_summary, 5, 0, 21),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [288] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 6),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [292] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 7, 0, 25),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [304] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_contract_path, 5, 0, 26),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [308] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [320] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_type, 3, 0, 0),
  [322] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 9, 0, 27),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [328] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [330] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 10, 0, 29),
  [332] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_gas, 1, 0, 0),
  [334] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [336] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_tx(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "tx",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
